// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayowwzkfhtyxthwpzmhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5b3d3emtmaHR5eHRod3B6bWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDY0NjQsImV4cCI6MjA3MTg4MjQ2NH0.1_axSLlML7j_JFuDRAycoZZBzpGI3kWr4MBhwOJaUgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});